<h1>Keras Intro</h1>

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

sns.set_style('darkgrid')

In [2]:
df = pd.read_csv('./data_sets/fake_reg.csv')
df.head()

price     feature1     feature2
0  461.527929   999.787558   999.766096
1  548.130011   998.861615  1001.042403
2  410.297162  1000.070267   998.844015
3  540.382220   999.952251  1000.440940
4  546.024553  1000.446011  1000.338531

In [3]:
df.shape

(1000, 3)

In [4]:
sns.pairplot(df)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X = df[['feature1', 'feature2']].values
y = df['price'].values

(X, y)

(array([[ 999.78755752,  999.7660962 ],
        [ 998.86161491, 1001.04240315],
        [1000.07026691,  998.84401463],
        ...,
        [1001.45164617,  998.84760554],
        [1000.77102275,  998.56285086],
        [ 999.2322436 , 1001.45140713]]),
 array([461.52792939, 548.13001146, 410.29716167, 540.38221981,
        546.02455292, 542.9836716 , 555.48566416, 417.56972453,
        373.14653122, 633.35029248, 624.24709206, 475.37241721,
        600.36844486, 532.83295175, 472.8353628 , 506.31229096,
        508.414406  , 610.4553519 , 323.65776198, 446.21230389,
        362.12270299, 433.41064026, 562.00257647, 637.30962074,
        522.80800754, 469.8028243 , 543.10992778, 565.43416994,
        530.03285381, 610.58016503, 482.55641188, 327.56004052,
        579.73083872, 448.42981468, 628.97709187, 536.79737216,
        570.06729543, 357.82557519, 612.08492732, 444.67970846,
        600.1186364 , 523.53312776, 512.94994495, 614.8813169 ,
        404.35303251, 643.68851807, 488.9

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [ ]:
X_train.shape, X_test.shape

((700, 2), (300, 2))

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
scaler = MinMaxScaler()

In [ ]:
scaler.fit(X_train)

MinMaxScaler()

In [ ]:
X_train = scaler.transform(X_train)

In [ ]:
X_test = scaler.transform(X_test)

In [ ]:
X_train, X_test

(array([[0.74046017, 0.32583248],
        [0.43166001, 0.2555088 ],
        [0.18468554, 0.70500664],
        ...,
        [0.54913363, 0.79933822],
        [0.2834197 , 0.38818708],
        [0.56282703, 0.42371827]]),
 array([[ 0.39533339,  0.38540671],
        [ 0.57300502,  0.74070924],
        [ 0.61294076,  0.65734264],
        [ 0.38169528,  0.73076311],
        [ 0.07776591,  0.46323644],
        [ 0.49421971,  0.68949258],
        [ 0.2065742 ,  0.70096247],
        [ 0.55141988,  0.41776773],
        [ 0.36812191,  0.69082394],
        [ 0.56465724,  0.3877465 ],
        [ 0.57048029,  0.71810824],
        [ 0.79569525,  0.47979901],
        [ 0.38488235,  0.41856516],
        [ 0.33142545,  0.42411972],
        [ 0.89361377,  0.63912775],
        [ 0.50191166,  0.39789174],
        [ 0.7159808 ,  0.43688384],
        [ 0.35812192,  0.92028225],
        [ 0.49989367,  0.85589311],
        [ 0.63965434,  0.59024789],
        [ 0.19053626,  0.34203634],
        [ 0.40982896,  0.

In [ ]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense