<h3>Numpy Intro</h3>

In [2]:
import numpy as np

In [4]:
mylist = [1, 2, 3]

In [5]:
np.array(mylist)

array([1, 2, 3])

In [6]:
nested_list = [
    [1, 2], 
    [3, 4],
    [5, 6]
]

In [7]:
print(np.array(nested_list))

[[1 2]
 [3 4]
 [5 6]]


In [9]:
np.arange(0, 10, 3)

array([0, 3, 6, 9])

In [11]:
np.zeros(30)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.zeros((4,10), dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [15]:
np.ones((4, 10), dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [21]:
np.linspace(0, 10, 51)

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,
        2.2,  2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,
        4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,
        6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,
        8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. ])

In [25]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
np.random.rand(4)

array([0.13691861, 0.11592817, 0.46240374, 0.36483547])

In [32]:
np.random.rand(3, 4)

array([[0.65988869, 0.75340231, 0.40563994, 0.45738761],
       [0.51901287, 0.20205839, 0.53091651, 0.98252264],
       [0.14536577, 0.20607586, 0.43187871, 0.36495719]])

In [33]:
np.random.randn(5, 5)

array([[-0.36010562,  1.98451131,  0.8987526 , -0.02248833,  1.51800081],
       [-0.29164628, -0.89176253, -1.12494506,  0.71701476, -0.44243003],
       [-0.47533021, -0.03356866, -0.91787142,  3.33138639,  1.23418818],
       [ 0.34597196,  0.74239279, -0.76428736,  0.47964337,  0.71117935],
       [ 0.37227763, -0.95281398, -1.60893857, -1.22486603,  1.21986266]])

In [41]:
np.random.randint(18, 70, (12, 5))

array([[39, 68, 35, 43, 22],
       [23, 59, 34, 62, 57],
       [25, 44, 40, 54, 66],
       [28, 24, 53, 44, 19],
       [41, 50, 57, 24, 67],
       [45, 20, 18, 63, 56],
       [67, 39, 68, 23, 34],
       [37, 55, 48, 22, 38],
       [59, 39, 57, 25, 36],
       [65, 64, 25, 49, 53],
       [57, 33, 51, 52, 56],
       [60, 64, 21, 34, 68]])

In [43]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [44]:
arr = np.arange(25)

In [46]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [45]:
ranarr = np.random.randint(0, 50, 10)

In [47]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [48]:
arr.shape

(25,)

In [50]:
arr = arr.reshape(5, 5)

In [51]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [52]:
ranarr.max()

39

In [54]:
ranarr.argmax()

7

In [55]:
ranarr.min()

2

In [56]:
ranarr.argmin()

9

In [58]:
ranarr.dtype

dtype('int64')