<h3>Numpy Intro</h3>


In [1]:
import numpy as np

In [2]:
mylist = [1, 2, 3]

In [3]:
np.array(mylist)

array([1, 2, 3])

In [4]:
nested_list = [
    [1, 2],
    [3, 4],
    [5, 6]
]

In [5]:
print(np.array(nested_list))

[[1 2]
 [3 4]
 [5 6]]


In [6]:
np.arange(0, 10, 3)

array([0, 3, 6, 9])

In [7]:
np.zeros(30)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.zeros((4, 10), dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [9]:
np.ones((4, 10), dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [10]:
np.linspace(0, 10, 51)

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,
        2.2,  2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,
        4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,
        6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,
        8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. ])

In [11]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
np.random.rand(4)

array([0.02429931, 0.9092324 , 0.33674741, 0.98189258])

In [13]:
np.random.rand(3, 4)

array([[0.28491291, 0.53102622, 0.87258618, 0.17804421],
       [0.5981947 , 0.2192519 , 0.33431547, 0.63252534],
       [0.77718427, 0.83087818, 0.92073094, 0.51583992]])

In [14]:
np.random.randn(5, 5)

array([[ 2.74830731e-02, -1.34848484e+00, -5.46981506e-01,
        -4.78637664e-01, -1.08195277e+00],
       [-3.87726353e-01,  1.02689363e+00,  2.25534395e+00,
        -5.69491450e-02,  1.49656801e+00],
       [ 4.76897461e-01,  3.42688780e-01, -2.45370828e-01,
        -2.58288438e-01,  1.28068928e+00],
       [-1.75109070e+00,  2.32278740e-01,  1.89659523e+00,
        -9.72894563e-04,  7.23368377e-01],
       [ 3.22973001e-01,  7.10754636e-01, -2.97606796e-01,
         7.40410991e-01,  1.30168895e+00]])

In [15]:
np.random.randint(18, 70, (12, 5))

array([[43, 29, 58, 22, 18],
       [57, 34, 58, 60, 60],
       [21, 32, 59, 33, 23],
       [69, 69, 30, 62, 68],
       [40, 63, 46, 69, 27],
       [57, 62, 18, 69, 41],
       [30, 50, 64, 50, 22],
       [48, 62, 42, 32, 39],
       [20, 27, 30, 23, 37],
       [36, 54, 37, 53, 56],
       [57, 37, 34, 23, 37],
       [19, 45, 62, 56, 53]])

In [16]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [17]:
arr = np.arange(25)

In [18]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [19]:
ranarr = np.random.randint(0, 50, 10)

In [20]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [21]:
arr.shape

(25,)

In [22]:
arr = arr.reshape(5, 5)

In [23]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
ranarr.max()

39

In [25]:
ranarr.argmax()

7

In [26]:
ranarr.min()

2

In [27]:
ranarr.argmin()

9

In [28]:
ranarr.dtype

dtype('int64')

<h3>Numpy Index Selection</h3>


In [30]:
import numpy as np

In [32]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
arr[6]

6

In [34]:
arr[1:5]

array([1, 2, 3, 4])

In [35]:
arr[:3]

array([0, 1, 2])

In [36]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [37]:
arr[:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [38]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
slice_of_arr = arr[:5]
slice_of_arr

array([0, 1, 2, 3, 4])

In [41]:
slice_of_arr[:] = 99
print(arr, slice_of_arr)

[99 99 99 99 99  5  6  7  8  9 10] [99 99 99 99 99]


In [42]:
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [49]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [50]:
arr_2d.shape

(3, 3)

In [54]:
arr_2d[0,2]

15

In [56]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [57]:
arr= np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
arr > 4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [59]:
arr >= 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True])

In [60]:
bool_arr = arr > 4
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [61]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [62]:
arr[arr<4]

array([0, 1, 2, 3])

<h3>Numpy Operations</h3>

In [63]:
import numpy as np

In [64]:
arr = np.arange(0, 10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [67]:
arr * 3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [68]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [69]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [70]:
arr / arr

/tmp/ipykernel_6210/3001117470.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [71]:
1 / 0

ZeroDivisionError: division by zero

In [72]:
1 / arr

/tmp/ipykernel_6210/1528351372.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [73]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [74]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [75]:
np.log(arr)

/tmp/ipykernel_6210/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [76]:
arr.sum()

45

In [78]:
arr.mean()

4.5

In [81]:
arr.max()

9

In [83]:
arr.min()

0

In [84]:
arr.var()

8.25

In [85]:
arr.std()

2.8722813232690143

In [87]:
np.sqrt(8.25)

2.8722813232690143

In [90]:
arr_2d = np.arange(0, 25).reshape(5, 5)
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [91]:
arr_2d.sum()

300

In [93]:
arr_2d.sum(axis=0)

array([50, 55, 60, 65, 70])

In [94]:
arr_2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])